name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          npm install

      - name: Build Frontend
        run: |
          npm run build

      - name: Validate SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VDS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 193.35.154.226 >> ~/.ssh/known_hosts

      - name: Copy Frontend to VDS
        uses: appleboy/scp-action@v0.1.1
        with:
          host: 193.35.154.226
          username: root
          key: ${{ secrets.VDS_SSH_KEY }}
          source: ./*
          target: /var/www/frontend
          debug: true


      - name: Start Frontend with PM2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa root@193.35.154.226 << 'EOF'
            cd /var/www/frontend/
            pm2 stop frontend-app || true
            pm2 delete frontend-app || true
            pm2 start "npm run start" --name "frontend-app"
          EOF

